#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: generic
sudo: true

git:
  depth: 1

env:
  global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1471"
    - BYOND_MACRO_COUNT=2
 
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

script:
    bash scripts/travis_pre_byond.sh

