#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: generic
sudo: false

git:
  depth: 1

env:
  global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1467"
    - BYOND_MACRO_COUNT=2
 
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386


script:
cd scripts
bash travis_pre_byond.sh

